apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{.Release.Name}}"
    app.kubernetes.io/component: server
  name: "{{.Release.Name}}-server"
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: "{{.Release.Name}}"
      app.kubernetes.io/component: server
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{.Release.Name}}"
        app.kubernetes.io/component: server
    spec:
      containers:
        - image: "ghcr.io/arikkfir/traefik-google-oidc-auth:{{.Chart.AppVersion | replace "+" "_"}}"
          name: server
          env:
            - name: "CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  name: "{{.Values.oauth.clientId.secretName}}"
                  key: "{{.Values.oauth.clientId.key}}"
            - name: "CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  name: "{{.Values.oauth.clientSecret.secretName}}"
                  key: "{{.Values.oauth.clientSecret.key}}"
            - name: "AUTH_SERVICE_HOST"
              value: "{{.Values.oauth.host}}"
            {{- if .Values.oauth.scopes }}
            - name: "SCOPES"
              value: "{{.Values.oauth.scopes}}"
            {{- end }}
            - name: "USER_COOKIE"
              value: "{{.Values.security.userCookie}}"
            - name: "SECRET"
              valueFrom:
                secretKeyRef:
                  name: "{{.Values.security.secret.secretName}}"
                  key: "{{.Values.security.secret.key}}"
            - name: "DOMAINS"
              value: "{{.Values.security.allowedDomains | join ","}}"
          ports:
            - containerPort: 8000
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      serviceAccountName: "{{.Release.Name}}-server"
