apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{.Release.Name}}"
    app.kubernetes.io/component: server
  name: "{{.Release.Name}}-server"
  namespace: {{.Release.Namespace}}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: "{{.Release.Name}}"
    app.kubernetes.io/component: server
  type: ClusterIP
