apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
  labels:
    app: "{{.Release.Name}}"
    app.kubernetes.io/component: server
  name: "{{.Release.Name}}-server"
  namespace: {{.Release.Namespace}}
