name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    shell: bash -eu {0}

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          check-latest: true
          go-version-file: go.mod
      - run: go vet ./...
      - run: go test -v -vet=off -race -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v3
        if: always()

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=ref,event=branch
            type=ref,event=pr
      - uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  helm:
    name: Helm
    runs-on: ubuntu-latest
    concurrency: push-helm-repository
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          version: 3.10.1
      - uses: benjlevesque/short-sha@v2.1
        id: shortsha
      - uses: actions/checkout@v3
        with:
          repository: arikkfir/arikkfir.github.io
          ref: master
          token: ${{ secrets.HELM_GITHUB_TOKEN }}
          path: arikkfir.github.io
      - run: helm package ./chart --app-version=${{ steps.shortsha.outputs.sha }} --version=${VERSION} --destination=./arikkfir.github.io/charts
        env:
          VERSION: 0.0.0-dev${{ github.run_number }}+${{ steps.shortsha.outputs.sha }}
      - name: push chart
        run: |
          helm repo index . --merge index.yaml --url https://arikkfir.github.io/charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Update charts repository"
          git push
        working-directory: arikkfir.github.io/charts
