name: Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash -eu {0}

jobs:

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
      - uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  helm:
    name: Helm
    needs: docker
    runs-on: ubuntu-latest
    concurrency: push-helm-repository
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          version: 3.10.1
      - uses: actions/checkout@v3
        with:
          repository: arikkfir/arikkfir.github.io
          ref: master
          token: ${{ secrets.HELM_GITHUB_TOKEN }}
          path: arikkfir.github.io
      - run: helm package ./chart --app-version=${{ github.ref_name }} --version=${{ github.ref_name }} --destination=./arikkfir.github.io/charts
      - name: push chart
        run: |
          helm repo index . --merge index.yaml --url https://arikkfir.github.io/charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Update charts repository"
          git push
        working-directory: arikkfir.github.io/charts
