name: Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-z][a-z0-9]*'

defaults:
  run:
    shell: bash -eu {0}

jobs:

  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ github.ref_name }}
      versionWithBuild: ${{ github.ref_name }}+${{ steps.shortsha.outputs.sha }}
    steps:
      - uses: benjlevesque/short-sha@v2.1
        id: shortsha

  test:
    name: Test
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          check-latest: true
          go-version-file: go.mod
      - run: go vet ./...
      - run: |
          go test -ldflags "-X 'github.com/${{ github.repository }}/internal.versionString=${VERSION}'" \
                  -v \
                  -vet=off \
                  -race \
                  -coverprofile=coverage.txt \
                  -covermode=atomic \
                  ./...
        env:
          VERSION: ${{ needs.version.outputs.versionWithBuild }}
      - uses: codecov/codecov-action@v3
        if: always()

  docker:
    name: Docker
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ needs.version.outputs.version }}
            type=raw,value=${{ needs.version.outputs.versionWithBuild }}
      - uses: docker/build-push-action@v3
        with:
          build-args: VERSION=${{ needs.version.outputs.versionWithBuild }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  helm:
    name: Helm
    needs: [version, docker]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.version.outputs.versionWithBuild }}
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          version: 3.10.1
      - run: helm package ./chart --app-version=${VERSION} --destination=. --version=${VERSION}
      - run: echo -n "${{ secrets.GITHUB_TOKEN }}" | helm registry login --username ${{ github.repository_owner }} --password-stdin ghcr.io
      - run: helm push traefik-google-oidc-auth-${VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}
